### PR TITLE
Add reverse and stereo spread parameter

### PR DESCRIPTION
**Pull request by davemollen**
@falkTX I would like to push an update for this effect. I can see you have a commit hash set as the version in the [makefile](https://github.com/moddevices/mod-plugin-builder/blob/master/plugins/package/dm-graindelay/dm-graindelay.mk). Do you update this manually or how is this supposed to work?

Also I made some changes and I'm not sure if this could potentially be breaking changes if someone used the beta version for a pedalboard. How is this normally managed?

One more thing; do you have an update on the following?
```
A small heads up, plugin will not load on 1.13.1 for the moment, as we needed to correct performance regressions with some component updates needed by the rust compiler.
We will fix it soon, sorry for the inconvenience.
```

### CODE REVIEW

**Comment by falkTX** [comment]
Typically you update the commit hash on the mod-plugin-builder through a pull request, that signals the wish for an update.

I do not have news regarding the broken rust builds yet.
On my last test I wasnt able to reproduce the issue, while it still happened on the cloud builder side.
Will try again soon.

**Comment by davemollen** [comment]
Alright, that makes sense. Does this mean updates to a plugin won't go through a beta phase?

**Comment by falkTX** [comment]
they will, once I get that working again.
currently MOD is focused on a big aida-x / AI model push, as that can bring sales in the short term. after this week I hope to have time for things like this

**Comment by davemollen** [comment]
Oh, sure. No pressure here. 

I meant; do updates for plugins that are out of the beta phase go through a beta phase again? Or are updates just pushed through? For this one this is purely hypothetical.

**Comment by falkTX** [comment]
no, I would just push it straight away as beta update after the MPB commit hash is updated

**Pull request merged**
